-- ============================================================
--  발주서 자동화 SaaS — Supabase Postgres 스키마 (Phase 0)
--  소스: backend/app/db.py init_db() (SQLite) 무손실 변환
--  변환 규칙:
--   - INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--     (BY DEFAULT: 데이터 이전 시 기존 id 명시 삽입 허용)
--   - 금액(원) 컬럼 -> BIGINT (int4 21억 한계 회피: 태무 99억·누적정산 대비)
--   - 수량/카운트 INTEGER -> INTEGER
--   - boolean-ish(is_active/active/cancel_at_period_end) -> INTEGER 유지 (코드 0/1 호환)
--   - REAL -> DOUBLE PRECISION
--   - BLOB -> BYTEA
--   - 시간 문자열(isoformat TEXT) -> TEXT 유지 (코드가 문자열 read/write)
--   - partial UNIQUE 인덱스: Postgres WHERE 절 그대로 지원
--  실행 순서: schema.sql -> rls_policies.sql -> seed.sql -> (migrate 스크립트)
-- ============================================================

-- ---------- 전역/운영 테이블 (테넌트 무관) ----------

CREATE TABLE IF NOT EXISTS cached_products (
    seller_product_id BIGINT PRIMARY KEY,          -- 쿠팡 외부 id (auto 아님)
    product_name      TEXT   NOT NULL,
    sale_price        BIGINT DEFAULT 0,            -- 금액
    stock             INTEGER DEFAULT 0,
    status            TEXT   DEFAULT '',
    vendor_item_id    BIGINT,
    category          TEXT   DEFAULT '',
    data_json         TEXT   DEFAULT '{}',
    updated_at        TEXT   NOT NULL
);

CREATE TABLE IF NOT EXISTS cached_orders (
    order_id          TEXT   PRIMARY KEY,           -- 쿠팡 외부 주문 id
    ordered_at        TEXT   NOT NULL,
    product_name      TEXT   NOT NULL,
    seller_product_id BIGINT DEFAULT 0,
    quantity          INTEGER DEFAULT 1,
    sale_price        BIGINT DEFAULT 0,            -- 금액
    status            TEXT   DEFAULT '',
    receiver_name     TEXT   DEFAULT '',
    data_json         TEXT   DEFAULT '{}',
    cached_at         TEXT   NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_sales (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT  NOT NULL,
    product_name   TEXT    NOT NULL,
    date           TEXT    NOT NULL,
    total_quantity INTEGER DEFAULT 0,
    total_revenue  BIGINT  DEFAULT 0,             -- 금액
    UNIQUE (product_id, date)
);

CREATE TABLE IF NOT EXISTS pricing_rules (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT  UNIQUE NOT NULL,
    product_name      TEXT    DEFAULT '',
    min_margin_pct    DOUBLE PRECISION DEFAULT 3.0,
    min_price         BIGINT  DEFAULT 0,           -- 금액
    max_price         BIGINT  DEFAULT 0,           -- 금액
    ad_stop_threshold DOUBLE PRECISION DEFAULT 1.0,
    active            INTEGER DEFAULT 1,
    created_at        TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS pricing_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT  NOT NULL,
    product_name  TEXT    DEFAULT '',
    old_price     BIGINT  NOT NULL,                -- 금액
    new_price     BIGINT  NOT NULL,                -- 금액
    margin_before DOUBLE PRECISION DEFAULT 0,
    margin_after  DOUBLE PRECISION DEFAULT 0,
    reason        TEXT    DEFAULT '',
    executed_at   TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS app_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS plans (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               TEXT UNIQUE NOT NULL,
    name               TEXT NOT NULL,
    price_krw          BIGINT NOT NULL DEFAULT 0,  -- 금액
    max_products       INTEGER,                    -- NULL = 무제한
    max_monthly_orders INTEGER,
    features_json      TEXT DEFAULT '{}',
    active             INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS supplier_price_snapshots (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_key          TEXT NOT NULL,
    supplier_name        TEXT NOT NULL,
    product_name         TEXT NOT NULL,
    option_name          TEXT NOT NULL,
    supplier_option_name TEXT NOT NULL,
    normalized_option_key TEXT NOT NULL,
    supplier_price       BIGINT NOT NULL DEFAULT 0, -- 금액
    checked_at           TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_supplier_price_snapshots_key
    ON supplier_price_snapshots (normalized_option_key, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_price_snapshots_monitor
    ON supplier_price_snapshots (monitor_key, checked_at DESC);

CREATE TABLE IF NOT EXISTS supplier_price_monitor_runs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date        TEXT NOT NULL,
    monitor_key     TEXT NOT NULL,
    supplier_name   TEXT DEFAULT '',
    product_name    TEXT DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'ok',
    total_items     INTEGER NOT NULL DEFAULT 0,
    changed_items   INTEGER NOT NULL DEFAULT 0,
    blue_count      INTEGER NOT NULL DEFAULT 0,
    red_count       INTEGER NOT NULL DEFAULT 0,
    same_count      INTEGER NOT NULL DEFAULT 0,
    output_filename TEXT DEFAULT '',
    error_message   TEXT DEFAULT '',
    checked_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_supplier_price_monitor_runs_date
    ON supplier_price_monitor_runs (run_date DESC, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_price_monitor_runs_key
    ON supplier_price_monitor_runs (monitor_key, checked_at DESC);

CREATE TABLE IF NOT EXISTS risk_snapshots (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL,
    product_name    TEXT DEFAULT '',
    score           DOUBLE PRECISION NOT NULL,
    level           TEXT NOT NULL,
    stock           INTEGER DEFAULT 0,
    avg_daily_sales DOUBLE PRECISION DEFAULT 0,
    days_remaining  DOUBLE PRECISION DEFAULT 0,
    margin_pct      DOUBLE PRECISION DEFAULT 0,
    snapshot_at     TEXT NOT NULL
);

-- ---------- 사용자/인증 ----------

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    email         TEXT UNIQUE,
    google_id     TEXT,                            -- partial unique index 로 관리
    kakao_id      TEXT,                            -- partial unique index 로 관리
    display_name  TEXT,
    avatar_url    TEXT,
    role          TEXT NOT NULL DEFAULT 'user',
    is_active     INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    auth_user_id  UUID UNIQUE                      -- Supabase Auth 연동(Phase 3에서 채움)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_kakao_id  ON users (kakao_id)  WHERE kakao_id  IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_google_id ON users (google_id) WHERE google_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS blocked_ips (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT NOT NULL,
    user_id    BIGINT,
    blocked_by BIGINT NOT NULL,
    reason     TEXT DEFAULT '',
    created_at TEXT NOT NULL,
    FOREIGN KEY (user_id)    REFERENCES users (id),
    FOREIGN KEY (blocked_by) REFERENCES users (id)
);
CREATE INDEX IF NOT EXISTS idx_blocked_ips ON blocked_ips (ip_address);

CREATE TABLE IF NOT EXISTS user_templates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    template_name TEXT NOT NULL,
    file_data     BYTEA NOT NULL,                  -- BLOB
    uploaded_at   TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS user_products (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL,
    product_label           TEXT NOT NULL,
    coupang_product_keyword TEXT NOT NULL,
    template_id             BIGINT,
    output_filename_pattern TEXT DEFAULT '{label}_{date}.xlsx',
    is_active               INTEGER NOT NULL DEFAULT 1,
    created_at              TEXT NOT NULL,
    FOREIGN KEY (user_id)     REFERENCES users (id),
    FOREIGN KEY (template_id) REFERENCES user_templates (id)
);

CREATE TABLE IF NOT EXISTS user_product_options (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_product_id        BIGINT NOT NULL,
    coupang_option_keyword TEXT NOT NULL,
    vendor_option_name     TEXT NOT NULL,
    template_target_cell   TEXT,
    unit_price_krw         BIGINT NOT NULL DEFAULT 0,  -- 마이그레이션 컬럼(정산 단가)
    created_at             TEXT NOT NULL,
    FOREIGN KEY (user_product_id) REFERENCES user_products (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT UNIQUE NOT NULL,
    plan_code            TEXT NOT NULL DEFAULT 'free',
    status               TEXT NOT NULL DEFAULT 'active',
    billing_key          TEXT,
    customer_key         TEXT,
    current_period_start TEXT,
    current_period_end   TEXT,
    cancel_at_period_end INTEGER DEFAULT 0,
    created_at           TEXT NOT NULL,
    updated_at           TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS billing_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    type            TEXT NOT NULL,
    amount_krw      BIGINT DEFAULT 0,               -- 금액
    toss_payment_key TEXT,
    toss_order_id   TEXT,
    raw_json        TEXT DEFAULT '{}',
    created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_billing_events_user ON billing_events (user_id);

CREATE TABLE IF NOT EXISTS usage_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    event_type    TEXT NOT NULL,
    product_label TEXT DEFAULT '',
    order_count   INTEGER DEFAULT 0,
    ym            TEXT NOT NULL,
    created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_usage_user_ym ON usage_logs (user_id, ym);

CREATE TABLE IF NOT EXISTS option_sales (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT NOT NULL,
    product_label          TEXT NOT NULL,
    coupang_option_keyword TEXT NOT NULL,
    vendor_option_name     TEXT DEFAULT '',
    quantity               INTEGER NOT NULL DEFAULT 0,
    external_order_id      TEXT DEFAULT '',
    ymd                    TEXT NOT NULL,
    ym                     TEXT NOT NULL,
    created_at             TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_option_sales_user_ymd       ON option_sales (user_id, ymd);
CREATE INDEX IF NOT EXISTS idx_option_sales_user_ym        ON option_sales (user_id, ym);
CREATE INDEX IF NOT EXISTS idx_option_sales_user_label_ymd ON option_sales (user_id, product_label, ymd);
CREATE UNIQUE INDEX IF NOT EXISTS idx_option_sales_unique_order_line
    ON option_sales (user_id, external_order_id, product_label, coupang_option_keyword, vendor_option_name)
    WHERE external_order_id <> '';

CREATE TABLE IF NOT EXISTS daily_settlement_snapshots (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT NOT NULL,
    product_label             TEXT NOT NULL,
    coupang_option_keyword    TEXT NOT NULL,
    vendor_option_name        TEXT DEFAULT '',
    quantity                  INTEGER NOT NULL DEFAULT 0,
    unit_price_krw            BIGINT NOT NULL DEFAULT 0,   -- 금액
    unit_price_source         TEXT NOT NULL DEFAULT 'missing',
    supplier_price_option_name TEXT DEFAULT '',
    settlement_krw            BIGINT NOT NULL DEFAULT 0,   -- 금액
    ymd                       TEXT NOT NULL,
    ym                        TEXT NOT NULL,
    logic_version             TEXT NOT NULL DEFAULT '',
    snapshot_at               TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_daily_settlement_snapshots_user_ymd
    ON daily_settlement_snapshots (user_id, ymd);
CREATE INDEX IF NOT EXISTS idx_daily_settlement_snapshots_user_ym
    ON daily_settlement_snapshots (user_id, ym);

CREATE TABLE IF NOT EXISTS order_batches (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    source_key      TEXT NOT NULL,
    batch_name      TEXT NOT NULL,
    template_name   TEXT NOT NULL,
    output_filename TEXT NOT NULL,
    total_rows      INTEGER NOT NULL DEFAULT 0,
    total_quantity  INTEGER NOT NULL DEFAULT 0,
    metadata_json   TEXT DEFAULT '{}',
    processed_at    TEXT NOT NULL,
    sync_status     TEXT NOT NULL DEFAULT 'pending',
    sync_error      TEXT DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX IF NOT EXISTS idx_order_batches_user_processed_at
    ON order_batches (user_id, processed_at DESC);

CREATE TABLE IF NOT EXISTS order_batch_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id            BIGINT NOT NULL,
    product_name        TEXT NOT NULL,
    platform_option_name TEXT DEFAULT '',
    supply_option_name  TEXT DEFAULT '',
    quantity            INTEGER NOT NULL DEFAULT 0,
    external_order_id   TEXT DEFAULT '',
    receiver_name       TEXT DEFAULT '',
    receiver_phone      TEXT DEFAULT '',
    receiver_address    TEXT DEFAULT '',
    memo                TEXT DEFAULT '',
    created_at          TEXT NOT NULL,
    FOREIGN KEY (batch_id) REFERENCES order_batches (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_order_batch_items_batch_id
    ON order_batch_items (batch_id);

-- ============================================================
-- 다음: rls_policies.sql 실행 (테넌트 격리), seed.sql (plans 시드)
-- ============================================================
